// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Determines where Codex stores CLI authentication credentials.
 */
export type AuthCredentialsStoreMode = "file" | "keyring" | "auto" | "ephemeral";
