// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";
import type { AutomationStatus } from "./AutomationStatus";
import type { AutomationTarget } from "./AutomationTarget";

/**
 * EXPERIMENTAL - durable recurring automation or heartbeat.
 */
export type Automation = { id: string, name: string, prompt: string, status: AutomationStatus, rrule: string, nextRunAt: bigint | null, lastRunAt: bigint | null, createdAt: bigint, updatedAt: bigint, model: string | null, reasoningEffort: ReasoningEffort | null, target: AutomationTarget, };
