// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request metadata for an open read handle.
 */
export type FsReadFileStatParams = { handleId: string, };
