// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read a bounded chunk from an open file at an absolute byte offset.
 */
export type FsReadFileReadParams = { handleId: string, offset: number,
/**
 * Requested upper bound. Values above `maxChunkBytes` are capped.
 */
maxBytes?: number | null, };
