// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bounded bytes returned by `fs/readFile/read`.
 */
export type FsReadFileReadResponse = { dataBase64: string,
/**
 * No bytes beyond this response were available at the time of the read.
 */
eof: boolean, };
