// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Open a file for bounded positional reads.
 */
export type FsReadFileOpenParams = {
/**
 * Client-supplied handle identifier scoped to this connection.
 */
handleId: string,
/**
 * Absolute path to open.
 */
path: AbsolutePathBuf, };
