// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Successful response for `fs/writeFile/write`.
 */
export type FsWriteFileWriteResponse = Record<string, never>;
