// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Successful response for `fs/writeFile/open`.
 */
export type FsWriteFileOpenResponse = {
/**
 * Maximum decoded bytes accepted by one write.
 */
maxChunkBytes: number, };
