// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Append one complete bounded chunk to an open write handle.
 */
export type FsWriteFileWriteParams = { handleId: string, dataBase64: string, };
