// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitResetCreditStatus } from "./RateLimitResetCreditStatus";
import type { RateLimitResetType } from "./RateLimitResetType";

export type RateLimitResetCredit = {
/**
 * Opaque backend identifier for this reset credit.
 */
id: string, resetType: RateLimitResetType, status: RateLimitResetCreditStatus,
/**
 * Unix timestamp in seconds when the credit was granted.
 */
grantedAt: bigint,
/**
 * Unix timestamp in seconds when the credit expires, or `null` if it does not expire.
 */
expiresAt: bigint | null, };
