// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Assigns a shell environment variable pattern to the include-only or exclude
 * set. Includes do not re-add variables removed by another exclude pattern.
 */
export type ShellEnvironmentPolicyFilter = "include" | "exclude";
