/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveredManagedLayers {
    #[serde(
        rename = "baseline",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub baseline: Option<Option<Vec<models::DeliveredTomlFragment>>>,
    #[serde(
        rename = "system_overlay",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub system_overlay: Option<Option<Vec<models::DeliveredTomlFragment>>>,
}

impl DeliveredManagedLayers {
    pub fn new() -> DeliveredManagedLayers {
        DeliveredManagedLayers {
            baseline: None,
            system_overlay: None,
        }
    }
}
